/*eslint max-len: ["error", { "code": 200 }]*/

export const FORM_FIELDS = {
    graduationYear: () => {
        const years = [];
        const currentYear = new Date().getFullYear();
        for (let i = currentYear; i >= 1990; i--) {
            years.push(i);
        }
        return years;
    },
    age: () => {
        const age = [];
        const maxAge = 40;
        for (let i = 17; i <= maxAge; i++) {
            age.push(i);
        }
        return age;
    },
    motivationLevel: [
        { value: '1', title: '1 - Not very motivated' },
        { value: '2', title: '2' },
        { value: '3', title: '3' },
        { value: '4', title: '4' },
        { value: '5', title: '5' },
        { value: '6', title: '6' },
        { value: '7', title: '7' },
        { value: '8', title: '8' },
        { value: '9', title: '9' },
        { value: '10', title: '10 - Very motivated' },
    ],
    militaryAffiliation: [
        'No Military Affiliation',
        'Army (Active)',
        'Air Force (Active)',
        'Navy (Active)',
        'Marine Corp (Active)',
        'Coast Guard (Active)',
        'Reserve Components',
        'National Guard',
        'Veteran (Not Active)',
        'Spouse/Dependent'
    ],
    levelOfEducation: [
        { value: '1211', title: 'No High School Diploma' },
        { value: '1212', title: 'GED' },
        { value: '1213', title: 'High School Diploma' },
        { value: '1214', title: 'Some College (1-29 credits)' },
        { value: '1216', title: 'Some College (30-59 credits)'},
        { value: '1217', title: 'Some College (60+ credits)' },
        { value: '1218', title: 'Associates Degree' },
        { value: '1219', title: 'Bachelors Degree' },
        { value: '1220', title: 'Masters Degree'},
        { value: '1221', title: 'Doctorates/PhD'}
        ],
    programOfInterest: [
        { value: '108948', 	campus_name: 'Newark, NJ',	            degree: 'Associate\'s',	                title: 'A.A.S. - Bus Admin-Management' },
        { value: '108952', 	campus_name: 'Newark, NJ',	            degree: 'Associate\'s',	                title: 'A.A.S. - Health Services Administration' },
        { value: '108954', 	campus_name: 'Newark, NJ',	            degree: 'Associate\'s',	                title: 'A.A.S. - Information Technology Management' },
        { value: '108957', 	campus_name: 'Newark, NJ',	            degree: 'Associate\'s',	                title: 'A.A.S. - Justice Studies - Criminal Justice' },
        { value: '108959', 	campus_name: 'Newark, NJ',	            degree: 'Associate\'s',	                title: 'A.A.S. - Marketing Communications' },
        { value: '108960', 	campus_name: 'Newark, NJ',	            degree: 'Associate\'s',	                title: 'A.A.S. - Medical Assistant' },
        { value: '108964', 	campus_name: 'Newark, NJ',	            degree: 'Bachelor\'s',                   title: 'B.B.A. - Bus Admin-Management' },
        { value: '108970', 	campus_name: 'Newark, NJ',	            degree: 'Bachelor\'s',                   title: 'B.B.A. - Marketing Communications' },
        { value: '108973', 	campus_name: 'Newark, NJ',	            degree: 'Bachelor\'s',	                title: 'B.S. - Information Technology Management' },
        { value: '108976', 	campus_name: 'Newark, NJ',	            degree: 'Undergraduate Certificate',	title: 'Certificate - Medical Assistant' },
        { value: '108978', 	campus_name: 'Newark, NJ',	            degree: 'Undergraduate Certificate',	title: 'Certificate - Patient Care Technician' },
        { value: '108947', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Bus Admin-Accounting' },
        { value: '108948', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Bus Admin-Management' },
        { value: '108949', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Fashion Merchandising & Management' },
        { value: '108950', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Financial Services' },
        { value: '108954', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Information Technology Management' },
        { value: '127783', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - International Business' },
        { value: '108957', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Justice Studies - Criminal Justice' },
        { value: '108958', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Legal Studies' },
        { value: '108959', 	campus_name: 'New York City, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Marketing Communications' },
        { value: '108963', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Accounting' },
        { value: '108964', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Bus Admin-Management' },
        { value: '108965', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Fashion Merchandising & Management' },
        { value: '108967', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - General Business' },
        { value: '108968', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Health Services Management' },
        { value: '108969', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - International Business' },
        { value: '108970', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Marketing Communications' },
        { value: '108973', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.S. - Information Technology Management' },
        { value: '108974', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.S. - Justice Studies - Criminal Justice' },
        { value: '108975', 	campus_name: 'New York City, NY',	    degree: 'Bachelor\'s',	                title: 'B.S. - Legal Studies' },
        { value: '108947', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Bus Admin-Accounting' },
        { value: '108948', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Bus Admin-Management' },
        { value: '108949', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Fashion Merchandising & Management' },
        { value: '108954', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Information Technology Management' },
        { value: '108955', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Interior Design' },
        { value: '127783', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - International Business' },
        { value: '108957', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Justice Studies - Criminal Justice' },
        { value: '108958', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Legal Studies' },
        { value: '108959', 	campus_name: 'Online',                  degree:	'Associate\'s', 	                title: 'A.A.S. - Marketing Communications' },
        { value: '108963', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.B.A. - Accounting' },
        { value: '108964', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.B.A. - Bus Admin-Management' },
        { value: '108965', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.B.A. - Fashion Merchandising & Management' },
        { value: '108968', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.B.A. - Health Services Management' },
        { value: '108969', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.B.A. - International Business' },
        { value: '108970', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.B.A. - Marketing Communications' },
        { value: '127785', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.F.A. - 3D Visualization' },
        { value: '108984', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.F.A. - BFA, Graphic Design' },
        { value: '108972', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.F.A. - Interior Design' },
        { value: '131229', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.S. - BS, Business Data Science' },
        { value: '108973', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.S. - Information Technology Management' },
        { value: '108974', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.S. - Justice Studies - Criminal Justice' },
        { value: '108975', 	campus_name: 'Online',                  degree:	'Bachelor\'s',	                title: 'B.S. - Legal Studies' },
        { value: '108977', 	campus_name: 'Online',                  degree:	'Undergraduate Certificate',	title: 'Certificate - Medical Insurance, Billing, and Coding' },
        { value: '129730', 	campus_name: 'Online',                  degree:	'Diploma',                      title: 'Diploma - Certificate in Interior Design' },
        { value: '108981', 	campus_name: 'Online - MBA',            degree:	'Master\'s',                     title: 'M.B.A. - Management' },
        { value: '108949', 	campus_name: 'White Plains, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Fashion Merchandising & Management' },
        { value: '108950', 	campus_name: 'White Plains, NY',	    degree: 'Associate\'s',	                title: 'A.A.S. - Financial Services' },
        { value: '108966', 	campus_name: 'White Plains, NY',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Financial Services' },
        { value: '108985', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - AAS, Surgical Technology' },
        { value: '108947', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - Bus Admin-Accounting' },
        { value: '108948', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - Bus Admin-Management' },
        { value: '108949', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - Fashion Merchandising & Management' },
        { value: '108951', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - Health Sciences' },
        { value: '108954', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - Information Technology Management' },
        { value: '108957', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - Justice Studies - Criminal Justice' },
        { value: '108960', 	campus_name: 'Woodbridge, NJ',	        degree: 'Associate\'s',	                title: 'A.A.S. - Medical Assistant' },
        { value: '108963', 	campus_name: 'Woodbridge, NJ',	        degree: 'Bachelor\'s',	                title: 'B.B.A. - Accounting' },
        { value: '108964', 	campus_name: 'Woodbridge, NJ',	        degree: 'Bachelor\'s',	                title: 'B.B.A. - Bus Admin-Management' },
        { value: '108973', 	campus_name: 'Woodbridge, NJ',	        degree: 'Bachelor\'s',	                title: 'B.S. - Information Technology Management' },
        { value: '108974', 	campus_name: 'Woodbridge, NJ',	        degree: 'Bachelor\'s',	                title: 'B.S. - Justice Studies - Criminal Justice' },
        { value: '108976', 	campus_name: 'Woodbridge, NJ',	        degree: 'Undergraduate Certificate',	title: 'Certificate - Medical Assistant' },
        { value: '108947', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Bus Admin-Accounting' },
        { value: '108948', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Bus Admin-Management' },
        { value: '108949', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Fashion Merchandising & Management' },
        { value: '108953', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Health Services Administration - Medical Insurance, Billing, and Coding' },
        { value: '108954', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Information Technology Management' },
        { value: '108957', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Justice Studies - Criminal Justice' },
        { value: '108958', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Legal Studies' },
        { value: '108959', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Marketing Communications' },
        { value: '108960', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Medical Assistant' },
        { value: '108961', 	campus_name: 'Woodland Park, NJ',	    degree: 'Associate\'s',	                title: 'A.A.S. - Surgical Technology' },
        { value: '108963', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Accounting' },
        { value: '108964', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Bus Admin-Management' },
        { value: '108968', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Health Services Management' },
        { value: '108970', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.B.A. - Marketing Communications' },
        { value: '108971', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.F.A. - Graphic Design' },
        { value: '108973', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.S. - Information Technology Management' },
        { value: '108974', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.S. - Justice Studies - Criminal Justice' },
        { value: '108975', 	campus_name: 'Woodland Park, NJ',	    degree: 'Bachelor\'s',	                title: 'B.S. - Legal Studies' },
        { value: '108982', 	campus_name: 'Woodland Park, NJ',	    degree: 'Undergraduate Certificate',	title: 'Certificate - Certificate in Practical Nurse' },
        { value: '108976', 	campus_name: 'Woodland Park, NJ',	    degree: 'Undergraduate Certificate',	title: 'Certificate - Medical Assistant' },
        { value: '108977', 	campus_name: 'Woodland Park, NJ',	    degree: 'Undergraduate Certificate',	title: 'Certificate - Medical Insurance, Billing, and Coding' },
        { value: '108978', 	campus_name: 'Woodland Park, NJ',	    degree: 'Undergraduate Certificate',	title: 'Certificate - Patient Care Technician' },
        { value: '108979', 	campus_name: 'Woodland Park, NJ',	    degree: 'Undergraduate Certificate',	title: 'Certificate - Practical Nurse' },
        { value: '108980', 	campus_name: 'Woodland Park, NJ',	    degree: 'Undergraduate Certificate',	title: 'Certificate - Surgical Processing Technician' },
        { value: '108981', 	campus_name: 'Woodland Park, NJ - MBA',	degree: 'Master\'s',                     title: 'M.B.A. - Management' },
    ],
    campusPreference: [
        {status: 'Active',	    value: '10580', 	title: 'Newark, NJ' },
        {status: 'Active',	    value: '10578', 	title: 'New York City, NY' },
        {status: 'Active',	    value: '10579', 	title: 'Online' },
        {status: 'Inactive',	value: '10583', 	title: 'Online - MBA' },
        {status: 'Inactive',	value: '10582', 	title: 'Paramus, NJ' },
        {status: 'Inactive',	value: '10576', 	title: 'White Plains, NY' },
        {status: 'Inactive',	value: '10581', 	title: 'Woodbridge, NJ' },
        {status: 'Active',	    value: '10577', 	title: 'Woodland Park, NJ' },
        {status: 'Inactive',	value: '10584', 	title: 'Woodland Park, NJ - MBA' },
    ],
    campusStateRestrictions: [
        { campus_id: '10579',	campus_name: 'Online',	        state: 'New Jersey (NJ)',	accept_reject: 'Accepted' },
        { campus_id: '10579',	campus_name: 'Online',	        state: 'New York (NY)',	    accept_reject: 'Accepted' },
        { campus_id: '10583',	campus_name: 'Online - MBA',	state: 'New Jersey (NJ)',	accept_reject: 'Accepted' },
        { campus_id: '10583',	campus_name: 'Online - MBA',	state: 'New York (NY)',	    accept_reject: 'Accepted' },
    ],
    startDate: [
        { value: 'Immediately',	        title: 'Immediately',	    validation: 'Accepted' },
        { value: '1-3 Months',          title: '1-3 Months',	    validation: 'Rejected' },
        { value: '4-6 Months',	        title: '4-6 Months',	    validation: 'Rejected' },
        { value: '7-12 Months',	        title: '7-12 Months',	    validation: 'Rejected' },
        { value: 'More than 1 Year',	title: 'More than 1 Year',	validation: 'Rejected' },
        { value: 'Not Sure',	        title: 'Not Sure',	        validation: 'Rejected' },
    ],
    states: [
        { value: 'AL', title: 'Alabama' },
        { value: 'AK', title: 'Alaska' },
        { value: 'AZ', title: 'Arizona' },
        { value: 'AR', title: 'Arkansas' },
        { value: 'CA', title: 'California' },
        { value: 'CO', title: 'Colorado' },
        { value: 'CT', title: 'Connecticut' },
        { value: 'DE', title: 'Delaware' },
        { value: 'FL', title: 'Florida' },
        { value: 'GA', title: 'Georgia' },
        { value: 'HI', title: 'Hawaii' },
        { value: 'ID', title: 'Idaho' },
        { value: 'IL', title: 'Illinois' },
        { value: 'IN', title: 'Indiana' },
        { value: 'IA', title: 'Iowa' },
        { value: 'KS', title: 'Kansas' },
        { value: 'KY', title: 'Kentucky' },
        { value: 'LA', title: 'Louisiana' },
        { value: 'ME', title: 'Maine' },
        { value: 'MD', title: 'Maryland' },
        { value: 'MA', title: 'Massachusetts' },
        { value: 'MI', title: 'Michigan' },
        { value: 'MN', title: 'Minnesota' },
        { value: 'MS', title: 'Mississippi' },
        { value: 'MO', title: 'Missouri' },
        { value: 'MT', title: 'Montana' },
        { value: 'NE', title: 'Nebraska' },
        { value: 'NV', title: 'Nevada' },
        { value: 'NH', title: 'New Hampshire' },
        { value: 'NJ', title: 'New Jersey' },
        { value: 'NM', title: 'New Mexico' },
        { value: 'NY', title: 'New York' },
        { value: 'NC', title: 'North Carolina' },
        { value: 'ND', title: 'North Dakota' },
        { value: 'OH', title: 'Ohio' },
        { value: 'OK', title: 'Oklahoma' },
        { value: 'OR', title: 'Oregon' },
        { value: 'PA', title: 'Pennsylvania' },
        { value: 'PR', title: 'Puerto Rico' },
        { value: 'RI', title: 'Rhode Island' },
        { value: 'SC', title: 'South Carolina' },
        { value: 'SD', title: 'South Dakota' },
        { value: 'TN', title: 'Tennessee' },
        { value: 'TX', title: 'Texas' },
        { value: 'AA', title: 'U.S. Armed Forces - Americas' },
        { value: 'AE', title: 'U.S. Armed Forces - Europe' },
        { value: 'AP', title: 'U.S. Armed Forces - Pacific' },
        { value: 'UT', title: 'Utah' },
        { value: 'VT', title: 'Vermont' },
        { value: 'VA', title: 'Virginia' },
        { value: 'WA', title: 'Washington' },
        { value: 'DC', title: 'Washington DC' },
        { value: 'WV', title: 'West Virginia' },
        { value: 'WI', title: 'Wisconsin' },
        { value: 'WY', title: 'Wyoming' },
    ]
};
